/* eslint-disable @typescript-eslint/no-explicit-any */
import { GraphClient } from '@optimizely/cms-sdk';
import { OptimizelyComponent } from '@optimizely/cms-sdk/react/server';
import { notFound } from 'next/navigation';
import React from 'react';

/**
 * Controls what happens when a user visits a path that is not generated by `generateStaticParams`
 * See: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamicparams
 */
export const dynamicParams = true;

/**
 * Generates static routes at build-time
 * See: https://nextjs.org/docs/app/api-reference/functions/generate-static-params
 */
export async function generateStaticParams() {
  if (!process.env.APPLICATION_HOST) {
    return [];
  }

  // Note: in this sample site, we do not use pagination for querying pages.
  // If a website has more than 100 pages, only 100 will be statically generated
  const query = `
  query GetPosts {
    _Page(limit: 100) {
      items {
        _metadata {
        	url {
            base
            default
          }
        }
      }
    }
  }
    `;

  const client = new GraphClient(process.env.OPTIMIZELY_GRAPH_SINGLE_KEY!, {
    graphUrl: process.env.OPTIMIZELY_GRAPH_GATEWAY,
  });
  const data = await client.request(query, {});

  return data._Page.items
    .filter(
      // Get only pages for current application
      (item: any) => item._metadata.url.base === process.env.APPLICATION_HOST
    )
    .map((item: any) => item._metadata.url.default)
    .map(
      // Remove leading slash
      (path: string) => (path.startsWith('/') ? path.slice(1) : path)
    )
    .map(
      // Remove trailing slash
      (path: string) => (path.endsWith('/') ? path.slice(0, -1) : path)
    )
    .filter((path: string) => path !== '')
    .map(
      // Format as required in Next.js
      (path: string) => ({
        slug: path.split('/'),
      })
    );
}

type Props = {
  params: Promise<{
    slug: string[];
  }>;
};

export default async function Page({ params }: Props) {
  const { slug } = await params;

  const client = new GraphClient(process.env.OPTIMIZELY_GRAPH_SINGLE_KEY!, {
    graphUrl: process.env.OPTIMIZELY_GRAPH_GATEWAY,
  });
  const c = await client.getContentByPath(`/${slug.join('/')}/`);

  if (c.length === 0) {
    notFound();
  }

  return <OptimizelyComponent opti={c[0]} />;
}
