'use client';
/**
 * Client helpers for /api/store/* — the single business path (§3).
 * The human UI calls these same routes as the WebMCP tools; no parallel logic.
 */
import type { StoreError } from '../../lib/store/engine';

export type ApiResult<T> =
  | { ok: true; data: T; sessionId: string | null; status: number }
  | { ok: false; error: StoreError; sessionId: string | null; status: number };

export async function storeFetch<T>(path: string, init?: RequestInit): Promise<ApiResult<T>> {
  let res: Response;
  try {
    res = await fetch(path, init);
  } catch {
    return {
      ok: false,
      error: {
        code: 'INVALID_ARGS',
        message: 'network request failed',
        hint: 'check the connection and retry',
      },
      sessionId: null,
      status: 0,
    };
  }
  const sessionId = res.headers.get('X-Stride-Session');
  let body: unknown = null;
  try {
    body = await res.json();
  } catch {
    /* empty body */
  }
  if (!res.ok) {
    const error: StoreError = (body as { error?: StoreError })?.error ?? {
      code: 'INVALID_ARGS',
      message: `request failed with status ${res.status}`,
      hint: 'retry the request',
    };
    return { ok: false, error, sessionId, status: res.status };
  }
  return { ok: true, data: body as T, sessionId, status: res.status };
}

/**
 * 32-char idempotency key (matches ^[A-Za-z0-9._-]{8,32}$). Generated by the
 * CALLER (this UI) — never by domain, API, or tool code (ADR 0002).
 */
export function newIdempotencyKey(): string {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID().replace(/-/g, '');
  }
  let key = '';
  const alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789';
  for (let i = 0; i < 32; i++) key += alphabet[Math.floor(Math.random() * alphabet.length)];
  return key;
}

export { formatUsd } from '../../lib/store/format';
