import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import {
  BlankExperienceContentType,
  initContentTypeRegistry,
} from '@optimizely/cms-sdk';
import { initReactComponentRegistry } from '@optimizely/cms-sdk/react/server';

import './globals.css';
import Teaser, { TeaserContentType } from '@/components/base/Teaser';
import Editorial, { EditorialContentType } from '@/components/base/Editorial';
import Contact, { ContactContentType } from '@/components/base/Contact';
import StartPage, { StartContentType } from '@/components/Start';
import Product, { ProductContentType } from '@/components/Product';
import Standard, { StandardContentType } from '@/components/Standard';
import Notice, { NoticeContentType } from '@/components/base/Notice';
import News, { NewsContentType } from '@/components/News';
import Article, { ArticleContentType } from '@/components/base/Article';
import BlankSection from '@/components/base/BlankSection';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

initContentTypeRegistry([
  ArticleContentType,
  BlankExperienceContentType,
  ContactContentType,
  EditorialContentType,
  NewsContentType,
  NoticeContentType,
  ProductContentType,
  StartContentType,
  TeaserContentType,
  StandardContentType,
]);

initReactComponentRegistry({
  resolver: {
    Article,
    Contact,
    Editorial,
    News,
    Notice,
    Product,
    Standard,
    StartPage,
    Teaser,
    BlankSection,
  },
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
