name: Publish package to NPM
on:
  push:
    branches:
      - release/*
  release:
    types: [released]
jobs:
  npm_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup .npmrc file
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install (all) dependencies)
        run: pnpm  --filter "./packages/**" install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm -r --if-present test

      - name: Publish packages
        run: pnpm publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
